FORMAT: 1A
HOST: twistory.pythonanywhere.com/

#### Twistory


**Version: v1**

Resources

+ [State](<http://idb14.apiary-mock.com/states)
+ [Park](<http://idb14.apiary-mock.com/parks)
+ [Hike](<http://idb14.apiary-mock.com/hikes)


# Group States


## State Collection [/api/states]
+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/api/states>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
         "Utah": "/api/states/Utah"  
         
         "Texas": "/api/states/Texas"
        
         "California": "/api/states/California"
         }
        ```
        
### List the name and the path to its detailed page of all states [GET]
+ Response 200

    [State Collection][]



## State [/api/states/state_name]

+ Parameters
    + state_name (required, string, `GET /api/states/Texas`) 
    
+ Model (application/json)
    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/states.json/Utah>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "name": "Utah", "date_founded": "1/4/1896", "population": "29000872",
                   "size(sqml)": "84899", "video": "link to video", "flag": "link to pic of flags"
            "parks": {"Zion": "/api/parks/Zion"},
         }
        ```
      

### List all info of the state with the given name [GET]

+ Response 200 (application/json)

    [State][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }



# Group Parks

## Park Collection [/api/parks]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/api/parks>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
         "Zion" : "/api/parks/Zion",
         "Yosemite" : "/api/parks/Yosemite" 
         "Denail" : "/api/parks/Denail"
        }
        ```

### List the name and the path to its detailed page of all parks [GET]

+ Response 200 (application/json)

    [Park Collection][]


## Park [/api/parks/park_name]

+ Parameters
    + park_name (required, string,`GET /api/parks/Grand Cayon`) ...

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/api/parks/Yosemite>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "name": "Yosemite", "size(acres)": "747956", "date_founded": "12/02/1982", "image": "link to image",
            "max_elevation(ft)": 13114, "visitors(annual)": "100000", "video": "link to video,
            "state": "California, "hikes": {"Mirror Lake Loop": "/api/hikes/Mirror Lake Loop", "Hallet Peak": "/api/hikes/Hallet Peak"}        
        }
        ```

### List all info of the park with the given name [GET]

+ Response 200 (application/json)

    [Park][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }


# Group Hikes

## Hike Collection [/api/hikes]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/api/hikes>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "Mirror Lake Loop": "/api/hikes/Mirror Lake Loop"
        
            "Hallet Peak", "/api/hikes/Hallet Peak"
        ]
        ```



### List the name and the path to the detailed page of all hikes [GET]

+ Response 200 (application/json)

    [Hike Collection][]

## Hike [/api/hikes/hike_name]

+ Parameters
    + hike_name (required, string, `GET /api/hike/Mirror Lake Loop`)

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/api/hikes/Mirror Lake Loop>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "name": "Mirror Lake Loop", "distance(mile)": "5",
            "est_time(min)": "90 min", "difficulty": "moderate", "image": "link to pic"
            "park": "Yosemite"          
        } 
        ```


### List all info of the hike with the given name [GET]

+ Response 200 (application/json)

    [Hike][]   
    

+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }