FORMAT: 1A
HOST: twistory.pythonanywhere.com/

#### Twistory

Twistory API gives access to real world **Twitter data** and view _trending events_

**Version: v1**

Resources

+ [Handles](<http://idb14.apiary-mock.com/handles)
+ [Hashtag](<http://idb14.apiary-mock.com/hashtags)
+ [Clusters](<http://idb14.apiary-mock.com/clusters)


# Group Handles
Twitter Handle resources are _people/entities_ that are actively engaged on twitter 


## Handle Collection [/handles]
+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/handles>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
         "id": 1, "name": "KingJames", "picture": "link to pic"
         }, 
         {
         "id": 2, "name": "oscar11", "picture": "link to pic"
         },
         {
         "id": 3, "name": "kobebryant", "picture": "link to pic"
         }]
        ```
        
### List the name, id and profile picture of all handles [GET]
+ Response 200

    [Handle Collection][]



## Handle [/handles/handle_id]

+ Parameters
    + handle_id (required, integer, `GET /handles/234`) ... the id given to a handle by this website
    
+ Model (application/json)
    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/handles/1>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "id": 1, "name": "KingJames", "picture": "link to pic", "bio": "Current NBA player",
            "tweet": "link to this handle's tweeter website",
            "videos": [{"video": "link to video", "description": "dunk"}],
            "graphs": [{"graph": "link to graph", "description": "number of tweets in 2013"}],
            "related_handles": [{"id":3, "name": "kobebryant", "page": "/handles/3"}],
            "related_hashtags": [{"id":1, "name": "HeatsVsSpurs", "page": "/hashtags/1"},
                                 {"id":3, "name": "FreeAgency", "page": "/hashtags/3"}
                                ],
            "related_clusters": [{"id":1, "name":"MiamiHeat", "page": "/clusters/1"}]
        }
        ```
      

### List all info of the handle with the given id [GET]

+ Response 200 (application/json)

    [Handle][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }



# Group Hashtags
Hashtags are markers that denote a specific tweet

## Hashtag Collection [/hashtags]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/hashtags>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
         "id": 1, "name": "HeatsVsSpurs" 
        }, {
         "id": 2, "name": "WorldCup" 
        }, {
         "id": 3, "name": "FreeAgency"
        }]
        ```

### List the id and name of all hashtags [GET]

+ Response 200 (application/json)

    [Hashtag Collection][]


## Hashtag [/hashtags/hashtag_id]

+ Parameters
    + hashtag_id(required, integer,`GET /hashtags/45454`) ... the id given to a hashtag by this website

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/hashtags/1>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "hashtag_id": 1, "name": "HeatsVsSpurs", "description": "NBA final",
            "graphs": [{"graph": "link to graph", "description": "number of uses in 2013"}],
            "related_handles": [{"id":1, "name": "KingJames", "page": "/handles/1"}],
            "related_hashtags": [],
            "related_clusters": [{"id":1, "name":"MiamiHeat", "page": "/clusters/1"}]
        }
        ```

### List all info of the hashtag with the given id [GET]

+ Response 200 (application/json)

    [Hashtag][]
    
+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }


# Group Clusters
Clusters are groups that are associated with multiple handles and hashtags

## Cluster Collection [/clusters]

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/clusters>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        [{
            "id": 1, "name": "MiamiHeat"
         },
         {
            "id": 2, "name": "Brazil"
        }]
        ```



### List the id and name of all clusters [GET]

+ Response 200 (application/json)

    [Cluster Collection][]

## Cluster [/clusters/cluster_id]

+ Parameters
    + cluster_id(required, integer, `GET /clusters/2`) ... the id given to a cluster by this website

+ Model (application/json)

    + Headers
    
        ```
        Link: <http://idb14.apiary-mock.com/clusters/1>
        Date: <Tue, 15 Dec 2054 03:11:21 GMT>
        Accept-Language: <en-us>
        ```
    + Body
        ```
        {
            "id": 1, "name": "MiamiHeat", "description": "A NBA team",
            "graphs": [{"graphs": "link to graph", "description": "active period"}]
            "related_handles": [{"id":1, "name": "KingJames", "page": "/handles/1"}],
            "related_hashtags": [{"id":1, "name": "HeatsVsSpurs", "page": "/hashtags/1"}],
            "related_clusters": []            
        } 
        ```


### List all info of the cluster with the given id [GET]

+ Response 200 (application/json)

    [Cluster][]   
    

+ Response 404 (application/json)

        {
            "error": "This id does not exsit in the file."
        }
        